server:
  port: 8080

spring:
  application:
    name: ambrozio-backend
    
  datasource:
    url: jdbc:postgresql://localhost:5432/ambrozio_db
    username: ambrozio_admin
    password: ambrozio_password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate # MUDAMOS AQUI! O Flyway cria as tabelas, o Hibernate só valida.
    show-sql: true
    properties:
      hibernate:
        "format_sql": true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs